import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';
import { createBranchAndCommit, openPR } from '../lib/github.js';
import { isoWeek, format } from '../lib/date.js';
import { KEYWORDS_FILE } from '../lib/keywords.js';

const SITEMAP_PENDING_FILE = 'seo/sitemap-pending.json';

export async function createPR({ generatedPages, keywordsJsonContent, config, cwd = process.cwd() }) {
  const week = isoWeek();
  const branch = `seo/${week}`;

  // Build sitemap pending list
  const sitemapPending = loadSitemapPending(cwd);
  const locales = config.locales || [config.locale || 'de'];
  for (const page of generatedPages) {
    const slug = `/${page.locale === config.locales?.[0] ? '' : page.locale + '/'}${page.slug}`;
    if (!sitemapPending.slugs.includes(slug)) sitemapPending.slugs.push(slug);
  }

  // Add hreflang frontmatter for multi-locale pages
  const enrichedPages = locales.length > 1
    ? injectHreflang(generatedPages, locales)
    : generatedPages;

  const files = [
    ...enrichedPages.map(p => ({ path: p.filePath, content: p.markdown })),
    { path: KEYWORDS_FILE, content: JSON.stringify(keywordsJsonContent, null, 2) + '\n' },
    { path: SITEMAP_PENDING_FILE, content: JSON.stringify(sitemapPending, null, 2) + '\n' },
  ];

  const safeKeyword = (kw) => String(kw ?? '').replace(/\r?\n/g, ' ').slice(0, 200);
  const commitMsg = `seo: add landing pages for ${week}\n\n${generatedPages.map(p => `- ${safeKeyword(p.keyword)}`).join('\n')}`;

  console.log(chalk.blue(`  Creating branch ${branch}, committing ${files.length} files...`));

  await createBranchAndCommit({ files, message: commitMsg, cwd, repo: config.repo });

  const prBody = buildPRBody(enrichedPages, sitemapPending, config);
  const prUrl = await openPR({
    repo: config.repo,
    branch,
    title: `SEO: landing pages ${week} (${generatedPages.length} pages)`,
    body: prBody,
  });

  console.log(chalk.green(`  PR opened: ${prUrl}`));
  return prUrl;
}

function injectHreflang(pages, locales) {
  // Group by slug, add hreflang block to each locale's frontmatter
  const bySlug = {};
  for (const p of pages) {
    if (!bySlug[p.slug]) bySlug[p.slug] = {};
    bySlug[p.slug][p.locale] = p;
  }

  return pages.map(p => {
    const siblings = bySlug[p.slug];
    const hreflangLines = Object.entries(siblings)
      .map(([loc, sibling]) => `  ${loc}: /${loc === locales[0] ? '' : loc + '/'}${sibling.slug}`)
      .join('\n');

    const hreflangBlock = `hreflang:\n${hreflangLines}`;
    const markdown = p.markdown.replace(/^(---\n[\s\S]+?)\n---/, (_, fm) => `${fm}\n${hreflangBlock}\n---`);
    return { ...p, markdown };
  });
}

function loadSitemapPending(cwd) {
  const path = join(cwd, SITEMAP_PENDING_FILE);
  if (!existsSync(path)) return { updated: null, slugs: [] };
  try { return JSON.parse(readFileSync(path, 'utf8')); } catch { return { updated: null, slugs: [] }; }
}

function mdCell(str) {
  return String(str ?? '')
    .replace(/\r?\n/g, ' ')
    .replace(/\|/g, '\\|')
    .replace(/`/g, '\\`');
}

function buildPRBody(pages, sitemapPending, config) {
  const rows = pages.map(p =>
    `| ${mdCell(p.keyword)} | \`${mdCell(p.slug)}\` | ${mdCell(p.locale || config.locale)} | ${mdCell(p.score)} | ${mdCell(p.type)} |`
  ).join('\n');

  const sitemapNote = sitemapPending.slugs.length
    ? `\n## Sitemap\n\nAfter merging, ping Google:\n\`\`\`\ncurl "https://www.google.com/ping?sitemap=${config.gsc_property}/sitemap.xml"\n\`\`\`\n\nNew slugs in \`seo/sitemap-pending.json\`:\n${sitemapPending.slugs.map(s => `- \`${s}\``).join('\n')}`
    : '';

  return `## New landing pages

| Keyword | Slug | Locale | Score | Type |
|---|---|---|---|---|
${rows}

## Review checklist
- [ ] Tone and style on point
- [ ] Facts are correct
- [ ] Schema.org block looks right
- [ ] Internal links resolve
- [ ] CTA makes sense in context
${pages.some(p => p.locale) ? '- [ ] hreflang pairs match across locales' : ''}
${sitemapNote}

Generated by seo-cli on ${format(new Date())}

> **Reminder:** LCP threshold tightened to 2.0s in March 2026. Check PageSpeed after deploy.`;
}
