import chalk from 'chalk';
import { createBranchAndCommit, openPR } from '../lib/github.js';
import { isoWeek, format } from '../lib/date.js';

export async function createPR({ generatedPages, keywordsJsonContent, config, cwd = process.cwd() }) {
  const week = isoWeek();
  const branch = `seo/${week}`;

  const files = [
    ...generatedPages.map(p => ({ path: p.filePath, content: p.markdown })),
    { path: 'seo/keywords.json', content: JSON.stringify(keywordsJsonContent, null, 2) + '\n' },
  ];

  const commitMsg = `seo: add landing pages for ${week}\n\n${generatedPages.map(p => `- ${p.keyword}`).join('\n')}`;

  console.log(chalk.blue(`  Creating branch ${branch} and committing ${files.length} files...`));

  await createBranchAndCommit({ files, message: commitMsg, cwd });

  const prBody = buildPRBody(generatedPages);
  const prUrl = await openPR({
    repo: config.repo,
    branch,
    title: `SEO: landing pages ${week} (${generatedPages.length} pages)`,
    body: prBody,
  });

  console.log(chalk.green(`  PR opened: ${prUrl}`));
  return prUrl;
}

function buildPRBody(pages) {
  const rows = pages.map(p =>
    `| ${p.keyword} | ${p.slug} | ${p.score} | ${p.type} |`
  ).join('\n');

  return `## New landing pages

| Keyword | Slug | Score | Type |
|---|---|---|---|
${rows}

## Checklist
- [ ] Tone and style on point
- [ ] Facts correct
- [ ] CTA makes sense in context
- [ ] Internal links work

Generated by seo-cli on ${format(new Date())}`;
}
